### ISSUE TITLE
package.json里怎么没有grunt？

### ISSUE THREAD

**Issue by xuzhijun** [Cola-Org/cola-ui#2]
每次npm i 完都要再装一遍grunt才能build，npm版本3.3.6

**Comment by AlexTong** [comment]
非常感谢您的关注与提醒。
grunt 命令需要全局安装grunt-cli

```
#安装命令
 npm install -g grunt-cli 
```

**Comment by xuzhijun** [comment]
grunt和grunt-cli都是全局安装的
![grunt](https://cloud.githubusercontent.com/assets/1052020/11265828/7d0ad57a-8eda-11e5-99ff-906ee59997c5.png)

**Comment by AlexTong** [comment]
在cola-ui目录下执行npm install 安装node 资源

```
npm install
```

再执行

```
grunt build
```

**Comment by xuzhijun** [comment]
![grunt2](https://cloud.githubusercontent.com/assets/1052020/11269995/25b3d8d2-8ef6-11e5-8b57-2e916092db90.png)

**Comment by xuzhijun** [comment]
1，sudo npm install 安装包
2，sudo npm install grunt-cli -g 安装全局grunt-cli
3，sudo npm install grunt -g 安装全局grunt
4，grunt build 失败

npm版本3.3.6，node版本 5.0.0

**Comment by xuzhijun** [comment]
我的理解是这样的，
grunt-cli是Grunt's command line interface，
全局安装grunt-cli是为了确保能使用命令行在任意文件夹下运行grunt这个命令。
然后grunt这个命令是否运行成功，却是需要在当前目录的node_modules下安装过grunt这个模块。

参考：
http://gruntjs.com/getting-started
官方给出的文档也只是说明了grunt-cli需要全局安装，
然后通过npm install，安装package.json中的模块。

**Comment by AlexTong** [comment]
grunt的插件依赖声明了的前提下grunt的依赖是可以不声明的，除非想限定使用的grunt版本，因为npm计算依赖关系时将自动帮你安装，就如maven的使用是一样的。而且友情提醒，请执行命令时要慎用sudo。
